website/models.py
from . import db 
from flask_login import UserMixin
from sqlalchemy.orm import relationship
import os
from dotenv import load_dotenv

load_dotenv()

class User(db.Model, UserMixin):
    __tablename__ = os.getenv('TABLENAME_U')
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(200))
    posts = db.relationship('BlogPost', backref='author')

class BlogPost(db.Model):
    __tablename__ = os.getenv('TABLENAME_B')
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250), unique=True, nullable=False)
    subtitle = db.Column(db.String(250), nullable=False)
    date = db.Column(db.String(250), nullable=False)
    body = db.Column(db.Text, nullable=False)
    img_url = db.Column(db.String(250), nullable=False)
    # Foreign Key to link Users (refer to primary key of a user)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

website/forms.py
from turtle import title
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, URL, Email
from flask_ckeditor import CKEditorField
from datetime import date

class NewPost(FlaskForm):
    title = StringField(label='Title', validators=[DataRequired()])
    subtitle = StringField(label='Subtitle', validators=[DataRequired()])
    img_url = StringField(label='Image URL', validators=[DataRequired(), URL()])
    body = CKEditorField(label='Content', validators=[DataRequired()])
    submit = SubmitField(label='Zapisz')

website/__init__.py
import os

from flask import Flask, render_template, redirect, url_for, request, abort
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_ckeditor import CKEditor
from os import path
from flask_login import LoginManager, current_user
from functools import wraps
from dotenv import load_dotenv

# ------------- Getting password from the environmental variable ----------------
load_dotenv()

db = SQLAlchemy()
DB_NAME = os.getenv('DB_NAME')

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
    # Suppressing the SQLALCHEMY_TRACK_MODIFICATIONS warning
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    # Connect to DB
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    # CSRF security
    app.config['CSRF_ENABLED'] = True
    # CKEditor, Bootstrap
    ckeditor = CKEditor(app)
    Bootstrap(app)

    db.init_app(app)

    # -------  Import views & auth  -------
    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    # -------  Import User db & create database  --------
    from .models import User, BlogPost
    create_database(app)

    # --------  Creating LoginManager class to cooperate with our Flask app  ---------
    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    # --------  Create a user_loader function  ---------
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    # # --------  Create an admin-only function  ----------
    # def admin_only(f):
    #     @wraps(f)
    #     def decorated_function(*args, **kwargs):
    #         if current_user.id != 1:
    #             return abort(403)
    #         return f(*args, **kwargs)
    #     return decorated_function

    return app

def create_database(app):
    if not path.exists("website/" + DB_NAME):
        db.create_all(app=app)
        print("Created database!")

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort
from .models import User
from . import db
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from functools import wraps


auth=Blueprint("auth", __name__)


# --------  Create an admin-only function  ----------
def admin_only(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.id != 1:
            return abort(403)
        return f(*args, **kwargs)
    return decorated_function

# ----------- SIGN-UP --------------
@auth.route("/sign-up", methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        if email_exists:
            flash('Email is already in use.', category='error')
        elif username_exists:
            flash('Username is already in use.', category='error')
        elif password1 != password2:
            flash('Password don\'t match!', category='error')
        else:
            hashed_password = generate_password_hash(password1, method= "pbkdf2:sha256", salt_length = 8)
            new_user = User(email=email, username=username, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('User created!')
            return redirect(url_for('views.blog'))


    return render_template("signup.html")


# ----------- LOGIN -------------
@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Successfully logged in.', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.blog'))
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Email don\'t exist. Please sign up.', category='error')

    return render_template('login.html')


# ------------ LOGOUT -------------
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

website/views.py
from flask import Blueprint, redirect, render_template, flash, session, url_for
from flask_login import login_required, current_user
from .models import BlogPost
from .forms import NewPost
from datetime import date, datetime
from . import db
from .auth import admin_only


views = Blueprint("views", __name__)

@views.route("/")
@views.route("/home")
def home():
    return render_template ("home.html")

@views.route("/blog")
@login_required
def blog():
    all_posts = BlogPost.query.all()
    return render_template ("blog.html", all_posts=all_posts)

@views.route("/add_new_post", methods=['GET','POST'])
@login_required
def add_new_post():
    form = NewPost()
    if form.validate_on_submit():
        title = form.title.data
        subtitle = form.subtitle.data
        img_url = form.img_url.data
        body = form.body.data
        author = current_user.id

        new_post =  BlogPost(
            title = title,
            subtitle = subtitle,
            img_url = img_url,
            body = body,
            date = datetime.now().strftime('%d/%m/%Y'),
            author_id = author
        )
        db.session.add(new_post)
        db.session.commit()

        flash('Post wprowadzony pomyślnie :)', category='success')
        return redirect(url_for('views.blog'))

    return render_template ("new_post.html", form=form)


@views.route("/post/<int:post_id>")
@login_required
def show_post(post_id):
    the_post = BlogPost.query.get(post_id)
    return render_template ("post.html", post=the_post)


@views.route("/edit-post/<int:post_id>", methods=['GET','POST'])
@admin_only
def edit_post(post_id):
    edited_post = BlogPost.query.get(post_id)
    edit_form = NewPost(obj=edited_post)

    if edit_form.validate_on_submit():
        edited_post.title = edit_form.title.data
        edited_post.subtitle = edit_form.subtitle.data
        edited_post.img_url = edit_form.img_url.data
        edited_post.date = datetime.now().strftime('%d/%m/%Y')
        edited_post.author_id = current_user.id

        db.session.commit()
        return redirect(url_for('views.blog'))

    return render_template("new_post.html", form=edit_form)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- BOOSTRAP STYLES -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- CSS styles -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/basestyles.css')}}">
    <!-- FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,300;0,400;0,700;1,100;1,300;1,400;1,600&family=Nunito+Sans:ital,wght@0,200;0,400;0,600;0,800;1,200;1,400;1,600&display=swap" rel="stylesheet">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/home">Home</a>
              </li>
              {% if not current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.sign_up')}}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.blog')}}">Blog</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
        {% if category == "success" %}
        <div class="alert alert-success alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% else %}
        <div class="alert alert-danger alter-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
    <!--JavaScript Bundle-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

website/templates/blog.html
{% extends 'base.html' %}
{% block title %} Blog {% endblock %}
{% block content %}

<!-- CSS styles -->
<link rel="stylesheet" href="{{url_for('static', filename='css/blog.css')}}">


<div class="header container-fluid">
  <h2>'Inside everyone there's a universe, a gigantic cosmos brimming with stars.'</h2>
  <div class="span">
    <span><b>Artem Chapeye, </b><c>The New Yorker, </c><b>28 Mar. 2022</c></span>
  </div>  
</div>
<div class="gray"></div>

{% if current_user.is_authenticated %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 mx-auto">
      {% for post in all_posts %}
      <div>
        <a href="{{url_for('views.show_post', post_id=post.id)}}">
          <h3>
            {{post.title}}
          </h3>
          <h4>
            {{post.subtitle}}
          </h4>
        </a>
        <p>Posted by
          <e>{{post.author.username}}</e>
          <f>, {{post.date}}</f>
          {% if current_user.id == 1 %}
          <a class ='x' href="#">✘</a>
          {% endif %}
        </p>
        <div class="line"></div>
      </div>
      <hr>
      {% endfor %}

      <!-- New Post -->
      {% if current_user.id == 1 %}
      <a class="btn float-right btn-lg" href="{{url_for('views.add_new_post')}}">Create New Post</a>
      {% endif %}
    </div>
  </div>
</div>
<hr>
{% endif %}


{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
<!-- CSS styles -->
<link rel="stylesheet" href="{{url_for('static', filename='css/homestyles.css')}}">

<div>
    <h1>Cosmos</h1>
</div>
<div class="text">
    <h2>This is a blog dedicated to the latest discoveries in space.</h2>
</div>

{% if not current_user.is_authenticated %}
<div class="signup-login container-md">
    <div class="row-1 row align-items-center justify-content-end">
        <div class="col-lg-8 col-md-9 col-sm-9">
            <p>Log in to see all the posts or sign-up if you are new here.</p>
        </div>
        <div class="col-lg-4 col-md-3 col-sm-3">
            <div class="row-2 row align-items-center justify-content-end">
                <div class="col">
                    <button type="button" class="btn btn-outline-light"><a href="{{url_for('auth.sign_up')}}">Sign-up</a></button>
                </div>
                <div class="col">
                    <button type="button" class="btn btn-outline-light"><a href="{{url_for('auth.login')}}">Log In</a></button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
<!-- BOOSTRAP STYLES -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- CSS styles -->
<link rel="stylesheet" href="{{url_for('static', filename='css/auth.css')}}">
<!-- FONTS -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,300;0,400;0,700;1,100;1,300;1,400;1,600&family=Nunito+Sans:ital,wght@0,200;0,400;0,600;0,800;1,200;1,400;1,600&display=swap" rel="stylesheet">

<h2 align="center">Login</h2>

<div class="whole-form">
  <form method="POST">
    <div class="mb-3">
      <label for="email" class="form-label">Email address</label>
      <input type="email" id="email" name ="email" class="form-control" placeholder="Enter Email">
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" id="password" name="password" class="form-control" placeholder="Password">
    </div>
    <div align="center">
      <button type="submit" class="btn btn-outline-light">Submit</button>
    </div>
  </form>
</div>
<!--JavaScript Bundle-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


{% endblock %}

website/templates/new_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Blog {% endblock %}
{% block content %}
<!-- CSS styles -->
<link rel="stylesheet" href="{{url_for('static', filename='css/new_post.css')}}">

<div class="text">
  {% if is_edit: %}
  <h2>Edit Post</h2>
  {% else: %}
  <h2>New Post</h2>
  {% endif %}
  <span class="subheading">You're going to make a great blog post!</span>
</div>

<div class="container">
  {{ wtf.quick_form(form, novalidate=True , button_map={"submit": "light"})}}
  {{ ckeditor.load() }}
  {{ ckeditor.config(name='body') }}
</div>


{% endblock %}

website/templates/post.html
{% extends 'base.html' %}
{% block title %} Post {% endblock %}
{% block content %}

<!-- CSS styles -->
<link rel="stylesheet" href="{{url_for('static', filename='css/post.css')}}">

<!-- Page Header -->
<div class="head container-fluid" style="background-image: url('{{post.img_url}}')">
    <div class="gray">
        <div class="title">
            <h2>{{post.title}}</h2>
        </div>
        <div class="subtitle">
            <h3>{{post.subtitle}}</h3>
        </div>
        <div class="author-date">
            <span>Posted by
                <a href="#">{{post.author.name}}</a>
                on {{post.date}}</span>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.body|safe }}
            <hr>
            {% if current_user.id == 1 %}
            <div>
                <a class="btn float-right btn-lg" href="{{url_for('views.edit_post', post_id=post.id)}}">Edit Post</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %} SignUp {% endblock %}
{% block content %}
<!-- CSS styles -->
<link rel="stylesheet" href="{{url_for('static', filename='css/auth.css')}}">

<h2 align="center">Sign Up</h2>

<div class="whole-form">
  <form method="POST">

    <div class="mb-3">
      <label for="email" class="form-label">Email address</label>
      <input type="email" id="email" name="email" class="form-control" placeholder="Enter Email">
    </div>
  
    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input type="username" id="username" name="username" class="form-control" placeholder="Username">
    </div>
  
    <div class="mb-3">
      <label for="password1" class="form-label">Password</label>
      <input type="password1" id="password1" name="password1" class="form-control" placeholder="Password">
    </div>
  
    <div class="mb-3">
      <label for="password2" class="form-label">Password Again</label>
      <input type="password2" id="password2" name="password2" class="form-control" placeholder="Repeat Password">
    </div>
  
    <div align="center">
      <button type="submit" class="btn btn-outline-light">Sign Up</button>
    </div>
  
  </form>
</div>

{% endblock %}